### ISSUE TITLE
Provider removal and potential reimplementation

### ISSUE THREAD

**Issue by Edvinest** [JDALab/film-central#8]
Was there any specific reason behind removing vidsrcme?
Could reimplementing it, and all the other domains owned by them yield good results?

**Comment by Unproductivv** [comment]
Is vadapav also affected by this change? It hasn't been working for me, and I assume that's why it's not working.

**Comment by Unproductivv** [comment]
> > Is vadapav also affected by this change? It hasn't been working for me, and I assume that's why it's not working.
> 
> Vadapav works fine for me, what were you trying to play?

Sorry for not getting back to you promptly, it's been a busy few weeks.

I'm trying to play Serial Experiments: Lain, and according to the output on mov-cli, there are... no results, even though vadapav definitely *does* have it.

Other media plays fine, as far as I can tell.

In addition to that, vidsrcto is outputting a **giant** error block. No clue how to fix that, but I'll attach that here so that can be looked into:

[errorlog.txt](https://github.com/user-attachments/files/16484444/errorlog.txt)

Until that is fixed, is there any way to change the default provider?

Thanks in advance.

**Comment by lowpolyv2** [comment]
> > > Is vadapav also affected by this change? It hasn't been working for me, and I assume that's why it's not working.
> > 
> > 
> > Vadapav works fine for me, what were you trying to play?
> 
> Sorry for not getting back to you promptly, it's been a busy few weeks.
> 
> I'm trying to play Serial Experiments: Lain, and according to the output on mov-cli, there are... no results, even though vadapav definitely _does_ have it.
> 
> Other media plays fine, as far as I can tell.
> 
> In addition to that, vidsrcto is outputting a **giant** error block. No clue how to fix that, but I'll attach that here so that can be looked into:
> 
> [errorlog.txt](https://github.com/user-attachments/files/16484444/errorlog.txt)
> 
> Until that is fixed, is there any way to change the default provider?
> 
> Thanks in advance.

Extremely sorry for the late response. That show doesn't seem to be available on vadapav, however it is available with the [`otaku-watcher`](https://github.com/JDALab/otaku-watcher) plugin. I recommend you always use that plugin for any anime. You can find it on pypi here: https://pypi.org/project/otaku-watcher/1.2.2/

**Comment by lowpolyv2** [comment]
and also yes "Serial Experiments" does work on the otaku watcher plugin I just streamed it. 😊
